ui:
- 'designer/client/*'
- 'designer/client/**/*'
- 'designer/submodules/*'
- 'designer/submodules/**/*'

client:
- 'designer/client/*'
- 'designer/client/**/*'

submodules:
- 'designer/submodules/*'
- 'designer/submodules/**/*'

docs:
- '**/*.md'
- 'docs/*'
- 'docs/**/*'
